version: "3.5"
services:

  cab-context:
    image: harbor.irtsysx.fr/cab/cabcontext:0.0.1
    environment:
      - CORRELATION_SERVICE=http://cab-correlation.cab-dev.svc.cluster.local:5300
      - DATABASE_URL=postgresql://postgres:postgres@db-postgres-context.cab-dev.svc.cluster.local:5434/cab-context
      - HOST_IP=$HOST_IP
      - FLASK_APP=app:create_app('dev')
      - PYTHONPATH=/code
      # - FLASK_ENV=development
    restart: unless-stopped
    command: python -m flask run --host=0.0.0.0 --reload
    ports:
      - 5100:5000
    depends_on:
      - db-postgres-context
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

  cab-event:
    image: harbor.irtsysx.fr/cab/cabevent:0.0.1
    restart: unless-stopped
    environment:
      - CARDS_PUBLICATION_SERVICE=http://cards-publication.cab-dev.svc.cluster.local:8080
      - GATEWAY_SERVICE=http://angular-ui.cab-dev.svc.cluster.local:80
      - HISTORIC_SERVICE=http://cab-historic.cab-dev.svc.cluster.local:5200
      - DATABASE_URL=postgresql://postgres:postgres@db-postgres-event.cab-dev.svc.cluster.local:5436/cab-event
      - HOST_IP=$HOST_IP
      - FLASK_APP=app:create_app('dev')
      - PYTHONPATH=/code
      # - FLASK_ENV=development
    command: python -m flask run --host=0.0.0.0 --reload
    ports:
      - 5000:5000
    depends_on:
      - db-postgres-event
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

  cab-historic:
    image: harbor.irtsysx.fr/cab/cabhistoric:0.0.1
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-postgres-historic.cab-dev.svc.cluster.local:5433/cab-historic
    restart: unless-stopped
    command: python -m flask run --host=0.0.0.0 --reload
    ports:
      - 5200:5000
    depends_on:
      - db-postgres-historic
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

  db-postgres-context:
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-context
    ports:
      - "5434:5432"
    volumes:
      - postgres_context_data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 50M

  db-postgres-event:
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-event
    ports:
      - "5436:5432"
    volumes:
      - postgres_event_data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 50M

  db-postgres-historic:
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-historic
    ports:
      - "5433:5432"
    volumes:
      - postgres_historic_data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 50M

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
        reservations:
          cpus: "0.05"
          memory: 256M

  frontend:
    image: harbor.irtsysx.fr/cab/frontend:0.0.1
    restart: unless-stopped
    configs:
      - source: ui-config-web-ui.json
        target: /usr/share/nginx/html/opfab/web-ui.json
      - source: ui-config-ui-menu.json
        target: /usr/share/nginx/html/opfab/ui-menu.json
      - source: nginx-conf-nginx-cors-permissive.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "3200:80"
    depends_on:
      - cab-correlation
      - cab-recommendation
      - cab-event
      - cab-context
      - cab-historic
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.05"
          memory: 50M

  cab-correlation:
    image: harbor.irtsysx.fr/cab/cabcorrelation:0.0.1
    restart: unless-stopped
    environment:
      - CARDS_PUBLICATION_SERVICE=http://cards-publication.cab-dev.svc.cluster.local:8080
      - GATEWAY_SERVICE=http://angular-ui.cab-dev.svc.cluster.local:80
      - HISTORIC_SERVICE=http://cab-historic.cab-dev.svc.cluster.local:5200
      - DATABASE_URL=postgresql://postgres:postgres@db-postgres-correlation.cab-dev.svc.cluster.local:5435/cab-correlation
      - HOST_IP=$HOST_IP
      - PYTHONPATH=/code
    command: python -m flask run --host=0.0.0.0 --reload
    ports:
      - 5300:5000
    depends_on:
      - db-postgres-correlation
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2048M
        reservations:
          cpus: "0.2"
          memory: 1024M

  db-postgres-correlation:
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-correlation
    ports:
      - "5435:5432"
    volumes:
      - postgres_correlation_data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 50M

  cab-recommendation:
    image: harbor.irtsysx.fr/cab/cabrecommendation:0.0.1
    restart: unless-stopped
    environment:
      - GATEWAY_SERVICE=http://angular-ui.cab-dev.svc.cluster.local:80
      - HOST_IP=$HOST_IP
      - FLASK_APP=app:create_app('dev')
      - FLASK_ENV=development
      - PYTHONPATH=/my_app
    command: python -m flask run --host=0.0.0.0 --reload
    ports:
      - 5400:5000
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 2048M
        reservations:
          cpus: "0.3"
          memory: 1024M

volumes:
  postgres_context_data:
  postgres_event_data:
  postgres_historic_data:
  postgres_correlation_data:
  pgadmin:


configs:
  ui-config-web-ui.json:
    file: ../ui-config/web-ui.json
  ui-config-ui-menu.json:
    file: ../ui-config/ui-menu.json
  nginx-conf-nginx-cors-permissive.conf:
    file: ../config/dev/cab/nginx-cors-permissive.conf
