cabcontext:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-context
    pullPolicy: Always
    tag: "1.2.2"

cabevent:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-event
    pullPolicy: Always
    tag: "1.2.2"

cabhistoric:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-historic
    pullPolicy: Always
    tag: "1.2.2"

cabrecommendation:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-recommendation
    pullPolicy: Always
    tag: "1.2.2"

cabcapitalization:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-capitalization
    pullPolicy: Always
    tag: "1.2.2"

frontend:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-standalone-frontend
    pullPolicy: Always
    tag: "1.2.2"