version: "3.5"
services:

  cabevent:
    container_name: cab_event
    image: cab/cabevent
    build:
      context: ../../../backend
      dockerfile: Event-Service-Dockerfile
    restart: unless-stopped
    environment:
      - CARDS_PUBLICATION_SERVICE=http://cards-publication:8080
      - GATEWAY_SERVICE=http://frontend:80
      - HISTORIC_SERVICE=http://cabhistoric:5000
      - DATABASE_URL=postgresql://postgres:postgres@db_postgres_event:5432/cab-event
      - HOST_IP=$HOST_IP
      - FLASK_APP=app:create_app('dev')
      - PYTHONPATH=/code
      - FLASK_ENV=development
      - URL_INTROSPECT=http://frontend:80/auth/check_token
      - KEYCLOAK_SERVER_URL=http://frontend:80/auth/
      - OPFAB_CLIENT_SECRET=opfab-keycloak-secret
    command: sh -c "./entrypoint.sh"
    ports:
      - 5000:5000
    volumes:
      - ../../../backend/event-service:/code
    networks:
      - light-cab-docker_default
    depends_on:
      - db_postgres_event

  cabhistoric:
    container_name: cabhistoric
    image: cab/cabhistoric
    build:
      context: ../../../backend/historic-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db_postgres_historic:5432/cab-historic
      - FLASK_APP=app:create_app('dev')
      - FLASK_ENV=development
      - URL_INTROSPECT=http://frontend:80/auth/check_token
      - KEYCLOAK_SERVER_URL=http://frontend:80/auth/
      - OPFAB_CLIENT_SECRET=opfab-keycloak-secret
    restart: unless-stopped
    command: sh -c "./entrypoint.sh"
    ports:
      - 5200:5000
    volumes:
      - ../../../backend/historic-service:/code
    networks:
      - light-cab-docker_default
    depends_on:
      - db_postgres_historic


  db_postgres_event:
    container_name: db_postgres_event
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-event
    ports:
      - "5436:5432"
    volumes:
      - postgres_event_data:/var/lib/postgresql/data/
    networks:
      - light-cab-docker_default

  db_postgres_historic:
    container_name: db_postgres_historic
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-historic
    ports:
      - "5433:5432"
    volumes:
      - postgres_historic_data:/var/lib/postgresql/data/
    networks:
      - light-cab-docker_default

  frontend:
    container_name: frontend
    build:
      context: ../../../frontend/main
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - "./ui-config:/usr/share/nginx/html/opfab"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3200:80"
    networks:
      - light-cab-docker_default
    depends_on:
      - cabevent

networks:
  light-cab-docker_default:
    external: true

volumes:
  postgres_event_data:
  postgres_historic_data:

