version: "3.5"
services:

  cabcontext:
    container_name: cab_context
    image: harbor.irtsysx.fr/cab/cabcontext
    build:
      context: ../../../backend
      dockerfile: Context-Service-Dockerfile
    environment:
      - CORRELATION_SERVICE=http://cab_correlation:5000
      - DATABASE_URL=postgresql://postgres:postgres@db_postgres_context:5432/cab-context
      - HOST_IP=$HOST_IP
      - FLASK_APP=app:create_app('dev')
      - PYTHONPATH=/code
      # - FLASK_ENV=development
    restart: unless-stopped
    command: sh -c "./entrypoint.sh"
    ports:
      - 5100:5000
    volumes:
      - ../../../backend/context-service:/code
    networks:
      - cab-docker_default
    depends_on:
      - db_postgres_context

  cabevent:
    container_name: cab_event
    image: harbor.irtsysx.fr/cab/cabevent
    build:
      context: ../../../backend
      dockerfile: Event-Service-Dockerfile
    restart: unless-stopped
    environment:
      - CARDS_PUBLICATION_SERVICE=http://cards-publication:8080
      - GATEWAY_SERVICE=http://angular-ui:80
      - HISTORIC_SERVICE=http://cabhistoric:5000
      - DATABASE_URL=postgresql://postgres:postgres@db_postgres_event:5432/cab-event
      - HOST_IP=$HOST_IP
      - FLASK_APP=app:create_app('dev')
      - PYTHONPATH=/code
      # - FLASK_ENV=development
    command: sh -c "./entrypoint.sh"
    ports:
      - 5000:5000
    volumes:
      - ../../../backend/event-service:/code
    networks:
      - cab-docker_default
    depends_on:
      - db_postgres_event

  cabhistoric:
    container_name: cabhistoric
    image: harbor.irtsysx.fr/cab/cabhistoric
    build:
      context: ../../../backend/historic-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db_postgres_historic:5432/cab-historic
    restart: unless-stopped
    command: sh -c "./entrypoint.sh"
    ports:
      - 5200:5000
    volumes:
      - ../../../backend/historic-service:/code
    networks:
      - cab-docker_default
    depends_on:
      - db_postgres_historic

  db_postgres_context:
    container_name: db_postgres_context
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-context
    ports:
      - "5434:5432"
    volumes:
      - postgres_context_data:/var/lib/postgresql/data/
    networks:
      - cab-docker_default

  db_postgres_event:
    container_name: db_postgres_event
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-event
    ports:
      - "5436:5432"
    volumes:
      - postgres_event_data:/var/lib/postgresql/data/
    networks:
      - cab-docker_default

  db_postgres_historic:
    container_name: db_postgres_historic
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-historic
    ports:
      - "5433:5432"
    volumes:
      - postgres_historic_data:/var/lib/postgresql/data/
    networks:
      - cab-docker_default

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - cab-docker_default
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: harbor.irtsysx.fr/cab/frontend
    build:
      context: ../../../frontend/main
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - "./ui-config:/usr/share/nginx/html/opfab"
      - "./nginx-cors-permissive.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3200:80"
    networks:
      - cab-docker_default
    depends_on:
      - cabcorrelation
      - cabrecommendation
      - cabevent
      - cabcontext
      - cabhistoric

  cabcorrelation:
    container_name: cab_correlation
    image: harbor.irtsysx.fr/cab/cabcorrelation
    build:
      context: ../../../backend
      dockerfile: Correlation-Service-Dockerfile
    restart: unless-stopped
    environment:
      - CARDS_PUBLICATION_SERVICE=http://cards-publication:8080
      - GATEWAY_SERVICE=http://angular-ui:80
      - HISTORIC_SERVICE=http://cabhistoric:5000
      - DATABASE_URL=postgresql://postgres:postgres@db_postgres_correlation:5432/cab-correlation
      - HOST_IP=$HOST_IP
      - PYTHONPATH=/code
    command: sh -c "./entrypoint.sh"
    ports:
      - 5300:5000
    volumes:
      - ./../../../backend/correlation-service:/code
    networks:
      - cab-docker_default
    depends_on:
      - db_postgres_correlation

  db_postgres_correlation:
    container_name: db_postgres_correlation
    image: postgres:14.7
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cab-correlation
    ports:
      - "5435:5432"
    volumes:
      - postgres_correlation_data:/var/lib/postgresql/data/
    networks:
      - cab-docker_default

  cabrecommendation:
    container_name: cab_recommendation
    image: harbor.irtsysx.fr/cab/cabrecommendation
    build:
      context: ../../../backend
      dockerfile: Recommendation-Service-Dockerfile
    restart: unless-stopped
    environment:
      - GATEWAY_SERVICE=http://angular-ui:80
      - HOST_IP=$HOST_IP
      - FLASK_APP=app:create_app('dev')
      - FLASK_ENV=development
      - PYTHONPATH=/my_app
    command: sh -c "./entrypoint.sh"
    ports:
      - 5400:5000
    volumes:
      - ./../../../backend/recommendation-service:/my_app
    networks:
      - cab-docker_default

networks:
  cab-docker_default:
    external: true

volumes:
  postgres_context_data:
  postgres_event_data:
  postgres_historic_data:
  postgres_correlation_data:
  pgadmin:
