apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f cab-assistant-platform.yaml
    kompose.image-pull-secret: regcred
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: cab-historic
  name: cab-historic
  
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cab-historic
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f cab-assistant-platform.yaml
        kompose.image-pull-secret: regcred
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/chart-default: "true"
        io.kompose.service: cab-historic
    spec:
      containers:
        - args:
            - python
            - -m
            - flask
            - run
            - --host=0.0.0.0
            - --reload
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db-postgres-historic.cab-dev.svc.cluster.local:5432/cab-historic
          image: harbor.irtsysx.fr/cab/cab-historic:0.0.1
          name: cab-historic
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "512Mi"
            requests:
              cpu: 200m
              memory: "256Mi"
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
