apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f cab-assistant-platform.yaml
    kompose.image-pull-secret: regcred
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
  
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f cab-assistant-platform.yaml
        kompose.image-pull-secret: regcred
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/chart-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: harbor.irtsysx.fr/cab/cab-frontend:0.0.1
          name: frontend
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: "128Mi"
            requests:
              cpu: 50m
              memory: "64Mi"
          volumeMounts:
            - mountPath: /usr/share/nginx/html/opfab/web-ui.json
              name: ui-config-web-ui
              subPath: web-ui.json
            - mountPath: /usr/share/nginx/html/opfab/ui-menu.json
              name: ui-config-ui-menu
              subPath: ui-menu.json
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-conf-nginx-cors-permissive
              subPath: default.conf
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: web-ui.json
                path: web-ui.json
            name: ui-config-web-ui
          name: ui-config-web-ui
        - configMap:
            items:
              - key: ui-menu.json
                path: ui-menu.json
            name: ui-config-ui-menu
          name: ui-config-ui-menu
        - configMap:
            items:
              - key: nginx-cors-permissive.conf
                path: default.conf
            name: nginx-conf-nginx-cors-permissive
          name: nginx-conf-nginx-cors-permissive
status: {}
