apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f cab-assistant-platform.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
  
spec:
  ports:
    - name: "3200"
      port: 3200
      targetPort: 80
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
