titre = "API PowerGrid - InteractiveAI"

[Connexion]
login_port = "auth/token"
cab_server_url_1 = "http://frontend.cab-dev.irtsystemx.org/"
cab_server_url_2 = "http://192.168.211.95:3200/"
cab_server_url_3 = "http://192.168.208.57:3200/"

[Outputs]
activate = "yes"

[Outputs.Events]
event_port = "cab_event/api/v1/events"

[Outputs.Context]
context_port = "cabcontext/api/v1/contexts"
tempo = 30

[Inputs.Act]
url = "http://192.168.209.166:5100/api/v1/recommendations"
