titre = "Simulator configuration"
env_name = "Ressources/ai4realnet_large"
env_seed = 2118338672
scenario_name = "2035-01-15_0"
time_step_forecast = 3
duration_step_forecast = 3
refresh_frequency_step = 3
step_start_security_analysis = 5
assistant_path = ""
assistant_seed = 1227139268
stepDuration_s = 0
scenario_first_step = 5
