#  POPULATE THE USER DATABASE ON INIT
# !!!! WARNING: VALUES SHOULD BE CHANGED FOR PRODUCTION MODE !!!!
#

spring:
  application:
    name: users

operatorfabric.users.default:
  users:
    - login: admin
      groups: ["ADMIN"]
      entities: ["SNCF","ORANGE", "ATM", "PowerGrid"]
    - login: ilyes
      firstname : Ilyes
      lastname : KAANICH
      groups: ["Dispatcher","ReadOnly"]
      entities: ["IRT_MAIN"]
    - login: sncf_user
      groups: ["Planner", "ReadOnly"]
      entities: ["SNCF"]
    - login: orange_user
      groups: [ "PowerGrid","ADMIN","ReadOnly","Dispatcher"]
      entities: [ "ORANGE" ]
    - login: atm_user
      groups: ["ReadOnly","Dispatcher"]
      entities: ["ATM"]
    - login: powergrid_user
      groups: [ "PowerGrid","ADMIN","ReadOnly","Dispatcher"]
      entities: [ "PowerGrid" ]
  groups:
    - id: ADMIN
      name: ADMINISTRATORS
      description: The admin group
    - id: PowerGrid
      name: RTE France
      description: RTE TSO Group
      realtime: false
    - id: Dispatcher
      name: Dispatcher
      description: Dispatcher Group
      realtime: true
    - id: Planner
      name: Planner
      description: Planner Group
      realtime: true
    - id: Supervisor
      name: Supervisor
      description: Supervisor Group
      realtime: true
    - id: Manager
      name: Manager
      description: Manager Group
      realtime: false
    - id: ReadOnly
      name: ReadOnly
      description: ReadOnly Group
      realtime: false
  entities:
   - id: SNCF
     name: National society of French railroads
     description: National society of French railroads
     parents : ["IRT_MAIN"]
   - id: ORANGE
     name: Orange
     description: Orange
     parents : ["IRT_MAIN"]
   - id: ATM
     name: ATM usecase
     description: ATM usecase
     parents : ["IRT_MAIN"]
   - id: PowerGrid
     name: Electricity Transmission Network
     description: Electricity Transmission Network
     parents : ["IRT_MAIN"]
   - id: IRT_MAIN
     name: IRT Control Centers
     description: IRT Control Centers
     entityAllowedToSendCard: false
