apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f operator-fabric.yaml
    kompose.controller.type: statefulset
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
  
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  serviceName: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chart-default: "true"
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:4.4.4-bionic
          name: mongodb
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: "104857600"
            requests:
              cpu: 100m
              memory: "52428800"
      restartPolicy: Always
  updateStrategy: {}
status:
  replicas: 0
