apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f operator-fabric.yaml
    kompose.controller.type: statefulset
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
  
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chart-default: "true"
        io.kompose.service: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3-management
          name: rabbit
          ports:
            - containerPort: 5672
              hostPort: 5672
              protocol: TCP
          resources:
            limits:
              cpu: 600m
              memory: "2147483648"
            requests:
              cpu: 300m
              memory: "1073741824"
          volumeMounts:
            - mountPath: /var/lib/rabbitmq/mnesia
              name: rabbit-persistance
      hostname: rabbit
      restartPolicy: Always
      volumes:
        - name: rabbit-persistance
          persistentVolumeClaim:
            claimName: rabbit-persistance
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: rabbit-persistance
        name: rabbit-persistance
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
status:
  replicas: 0
