variables:
  CONTEXT: "chart"
  DOCKER_COMPOSE: "cab-assistant-platform.yaml"

.kompose:
  stage: compose-convert
  image: debian:bookworm-slim
  interruptible: true
  before_script:
    - apt update && apt install -y curl
    - curl -L https://github.com/kubernetes/kompose/releases/download/v1.30.0/kompose-linux-amd64 -o kompose
    - chmod +x kompose
    - mv ./kompose /usr/local/bin/kompose
  script:
    - cd ${CONTEXT}
    - kompose convert -c -f $DOCKER_COMPOSE
  artifacts:
    paths:
      - ${DOCKER_COMPOSE::-5}
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == "test-ci"
    - if: $CI_COMMIT_BRANCH == "develop"


