# Fichier de configuration du simulateur
titre = "Simulator configuration"

env_name = "env_icaps_input_data_test"
env_seed = 2118338672
scenario_name = 'jan_28_1' # the scenario to play from env_name repository

assistant_name = "XD_silly_repo"
assistant_seed = 1227139268

	